-- MySQL Script generated by MySQL Workbench
-- Thu Mar 29 15:41:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ris
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ris
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ris` DEFAULT CHARACTER SET utf8 ;
USE `ris` ;

-- -----------------------------------------------------
-- Table `ris`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris`.`Patient` (
  `idPatient` INT NOT NULL AUTO_INCREMENT,
  `FName` VARCHAR(45) NOT NULL,
  `LName` VARCHAR(45) NOT NULL,
  `Minitial` VARCHAR(45) NOT NULL,
  `DOB` VARCHAR(45) NOT NULL,
  `SSN` VARCHAR(45) NOT NULL,
  `lastApp` VARCHAR(45) NULL,
  `nextApp` VARCHAR(45) NULL,
  `Height` VARCHAR(45) NULL,
  `Gender` VARCHAR(45) NULL,
  `Race` VARCHAR(45) NULL,
  `Weight` VARCHAR(45) NULL,
  PRIMARY KEY (`idPatient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ris`.`RadLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris`.`RadLogin` (
  `idRadLogin` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRadLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ris`.`MDLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris`.`MDLogin` (
  `idMDLogin` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idMDLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ris`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris`.`Report` (
  `idReport` INT NOT NULL AUTO_INCREMENT,
  `reportDesciption` VARCHAR(200) NULL,
  PRIMARY KEY (`idReport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ris`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris`.`Schedule` (
  `idSchedule` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATE NULL,
  `time` VARCHAR(45) NULL,
  PRIMARY KEY (`idSchedule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ris`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris`.`image` (
  `idimage` INT NOT NULL AUTO_INCREMENT,
  `image` BLOB NULL,
  `Report_idReport` INT NOT NULL,
  PRIMARY KEY (`idimage`, `Report_idReport`),
  INDEX `fk_image_Report_idx` (`Report_idReport` ASC),
  CONSTRAINT `fk_image_Report`
    FOREIGN KEY (`Report_idReport`)
    REFERENCES `ris`.`Report` (`idReport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ris`.`Billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris`.`Billing` (
  `OrderID` INT NOT NULL,
  `Patient_idPatient` INT NOT NULL,
  `ProDate` DATE NULL,
  `ProCost` DATE NOT NULL,
  `Adjustment` INT NULL,
  `ProDecs` VARCHAR(45) NULL,
  INDEX `fk_Billing_Patient1_idx` (`Patient_idPatient` ASC),
  PRIMARY KEY (`OrderID`),
  CONSTRAINT `fk_Billing_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `ris`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ris`.`TechLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris`.`TechLogin` (
  `idTechLogin` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTechLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ris`.`FrontLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris`.`FrontLogin` (
  `idFrontLogin` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFrontLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ris`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ris`.`appointment` (
  `idappointment` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `modality` VARCHAR(45) NOT NULL,
  `bodypart` VARCHAR(45) NULL,
  `notes` VARCHAR(45) NULL,
  `Patient_idPatient` INT NOT NULL,
  PRIMARY KEY (`idappointment`),
  INDEX `fk_appointment_Patient1_idx` (`Patient_idPatient` ASC),
  CONSTRAINT `fk_appointment_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `ris`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
