-- MySQL Script generated by MySQL Workbench
-- Fri Mar 23 14:18:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `idPatient` INT NOT NULL AUTO_INCREMENT,
  `FName` VARCHAR(45) NOT NULL,
  `LName` VARCHAR(45) NOT NULL,
  `M initial` VARCHAR(45) NULL,
  `DOB` VARCHAR(45) NOT NULL,
  `SSN` VARCHAR(45) NOT NULL,
  `lastApp` VARCHAR(45) NULL,
  `nextApp` VARCHAR(45) NULL,
  PRIMARY KEY (`idPatient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RadLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RadLogin` (
  `idRadLogin` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRadLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MDLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MDLogin` (
  `idMDLogin` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idMDLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PatientDemo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PatientDemo` (
  `Patient_idPatient` INT NOT NULL,
  `Height` VARCHAR(45) NULL,
  `Race` VARCHAR(45) NULL,
  `Gender` VARCHAR(45) NULL,
  `Weight` VARCHAR(45) NULL,
  PRIMARY KEY (`Patient_idPatient`),
  CONSTRAINT `fk_PatientDemo_Patient`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `mydb`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Report` (
  `idReport` INT NOT NULL AUTO_INCREMENT,
  `reportDesciption` VARCHAR(200) NULL,
  PRIMARY KEY (`idReport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Schedule` (
  `idSchedule` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATE NULL,
  `time` VARCHAR(45) NULL,
  PRIMARY KEY (`idSchedule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`image` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `image` BLOB NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Billing` (
  `PatientID` INT NOT NULL,
  `OrderID` INT NOT NULL,
  `ProDate` DATE NULL,
  `ProCost` DATE NOT NULL,
  `Adjustment` INT NULL,
  PRIMARY KEY (`PatientID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TechLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TechLogin` (
  `idTechLogin` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTechLogin`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
